name: Push to master

on:
  push:
    branch:
      - master
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  checks:
    uses: ./.github/workflows/lint-and-coverage.yaml
    secrets: inherit